name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получаем ваш код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Настраиваем Java для Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          # Включаем кэширование зависимостей Gradle для ускорения сборок
          cache: 'gradle'

      # Шаг 3: Выполняем команду сборки с помощью Gradle Wrapper
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Шаг 4: Загружаем готовый APK-файл как артефакт
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
